server {
  listen 80;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://automailer-backend:8080;
    proxy_set_header Host $host;
  }

  location / {
    index index.html;
    try_files $uri /index.html;
  }
}